### PR TITLE
a few tweaks as per Damian's request in the PR

### PR DESCRIPTION
**Pull request by parmentelat**
this is to clarify the comments and requests that Damian raised when merging #287

### CODE REVIEW

**Comment by parmentelat** [comment]
let me just repeat what I said in the first PR

> PS. I have not run that code, as the changes are small, and as I don't have the time right now;
I thought it was best that I answer quickly, especially as you said you would soon spend some time on this.

**Comment by damianavila** [comment]
>let me just repeat what I said in the first PR

That's ok, I will test it and merge it. Thanks for pushing it.

**Comment by damianavila** [comment]
Tested this OK, @parmentelat.
Can you please add a little bit of docs in this section: https://damianavila.github.io/RISE/customize.html#configuration-options. It should not be too exhaustive, just a paragraph with the new options. After that we can merge this one.

**Comment by parmentelat** [comment]
I added some material in `customize.rst; this is pushed in my branch

as a side note: when merging master on top of this branch, I ran into quite a few conflicts in the doc/ area
It feels like at some point or another some of those files have changed from DOS cr-lf format to Unix-style end-of-lines, does that make any sense ?

anyway I hope I did not break anything here

**Comment by damianavila** [comment]
> as a side note: when merging master on top of this branch, I ran into quite a few conflicts in the doc/ area

Someone contribute with docs some months ago and I realized the issue just yesterday. I think I have fixed it here: https://github.com/damianavila/RISE/pull/305

**Comment by damianavila** [comment]
Btw, thanks for the docs addition. Merging this one now.

**Pull request merged**
