### PR TITLE
load css through a relative url

### PR DESCRIPTION
**Pull request by parmentelat**
follow up to #479

### CODE REVIEW

**Comment by sbrunk** [comment]
Did a quick test using your branch locally and on binder and it loads `rise.css` correctly in both cases. 

It does not find `reveal.css` but I think that's unrelated (also occurs on master for me).

**Comment by parmentelat** [comment]
thanks for the report; but to clarify, with reveal.css nothing works, right ?

I'll try to release a new dev release with this pr as soon as Damian gives his go

**Comment by sbrunk** [comment]
Yes, it tries to load reveal.css, but gets a 404 which completely breaks the layout.

Note that I did not use development mode for testing this but installed RISE via pip instead like this:
```bash
pip install https://github.com/damianavila/RISE/archive/relative-url.zip
```
Not sure if this can make a difference here.

**Comment by damianavila** [comment]
> I'll try to release a new dev release with this pr as soon as Damian gives his go

Feel free to do so!

**Comment by damianavila** [comment]
> Note that I did not use development mode for testing this but installed RISE via pip instead like this:

That's probably the cause.

**Comment by parmentelat** [comment]
Hi
I did release 5.6.0.dev3 earlier today, just had not yet got around to announcing it

**Pull request merged**
