### PR TITLE
BUG: Fix broken shortcuts in notebook 4.1.

### PR DESCRIPTION
**Pull request by ssanderson**
The names of the shortcut actions changed.
c.f. https://github.com/jupyter/notebook/issues/887

### CODE REVIEW

**Comment by damianavila** [comment]
Looking into this this week... thanks @ssanderson

**Comment by zindy** [comment]
Hello, just to confirm, this fix has re-enabled shit-enter in RISE on both Linux and Windows.

**Comment by WeatherGod** [comment]
This PR also fixes the problem for me too.

**Comment by BioNinja** [comment]
This PR also fixes the problem for me on MAC, too

**Comment by damianavila** [comment]
Let's get this merged... sorry for the delay!!

**Pull request merged**
