### PR TITLE
Place slide titles automatically

### PR DESCRIPTION
**Pull request by anhi**
For my presentations, I needed a way to place individual slide titles into header or footer of the slide. This is a reasonably simple way to achieve this that works for me.

### CODE REVIEW

**Comment by damianavila** [comment]
I will take a look, thanks!

**Comment by damianavila** [comment]
Btw, I think this one supersede #218, am I right? If that is the case, please close the other PR. Thanks!

**Comment by anhi** [comment]
Good point, I've closed #218.

**Comment by damianavila** [comment]
Superseded by #296 (different mechanism but achieving the same end). Closing here. Thanks @anhi.

**Pull request closed without merging**
