### PR TITLE
Add Julia installation instructions

### PR DESCRIPTION
**Pull request by timholy**
I'm not sure if you want these here, but I thought I'd offer it and let you decide.

### CODE REVIEW

**Comment by damianavila** [comment]
Sure! There is currently a PR porting stuff from the README to real docs?
What about putting this change on that PR? https://github.com/damianavila/RISE/pull/281

Or maybe wait for me to review and merge that PR and then you can submit another one with this change on top of master?

**Comment by timholy** [comment]
That'd be fine, whatever you prefer.

**Comment by damianavila** [comment]
> That'd be fine, whatever you prefer.

I just merged the other PR, you can add your changes now in the file: https://github.com/damianavila/RISE/blob/master/doc/installation.rst

Thanks!

**Comment by damianavila** [comment]
In fact, I can merge this one now, but I would suggest to add this piece in the docs file as well. Thanks!

**Pull request merged**
