### PR TITLE
Add config option to scrolling slides.

### LINKED ISSUE #138: Enable scrolling using the config manager
It would be nice to be able to easily select whether individual slides should be scrollable, global on/global off, etc.

### PR DESCRIPTION
**Pull request by damianavila**
Fixes #138 

ping @swnesbitt, @jorisvandenbossche 

to enable it, you need to have:

```shell
damian-S400CA :: ~/.jupyter/nbconfig :: 
$ pwd
/home/damian/.jupyter/nbconfig
damian-S400CA :: ~/.jupyter/nbconfig :: 
$ cat livereveal.json 
{
  "scroll": true
}
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I can confirm this works! 

You now get a scrollbar on each slide so that the largest slide fits on it, but that is OK

**Comment by swnesbitt** [comment]
Awesome!  Thanks

Sent from my iPhone

--
Steve Nesbitt, Associate Professor
Department of Atmospheric Sciences, University of Illinois at Urbana-Champaign
105 S. Gregory St.<x-apple-data-detectors://1>, MC223, Urbana, IL 61801-3070  USA
voice : +1.217.244.3740<tel:+1.217.244.3740>  fax : +1.217.244.1752<tel:+1.217.244.1752>
internet : snesbitt@illinois.edu<mailto:snesbitt@illinois.edu> ; https://www.atmos.illinois.edu/people/snesbitt ; http://publish.illinois.edu/snesbitt

On Aug 25, 2015, at 5:03 AM, Joris Van den Bossche <notifications@github.com<mailto:notifications@github.com>> wrote:


I can confirm this works!

You now get a scrollbar on each slide so that the largest slide fits on it, but that is OK

**Comment by damianavila** [comment]
> You now get a scrollbar on each slide so that the largest slide fits on it, but that is OK

But IIRC, we had the same behavior before... put scroll bars in "one" specific slide IF the content is large than the view is not something we can do easily and probably involves modification in the core of Reveal.js itself (which was suggested to Reveal.js author but he is not interested to make it happen because conflict with other things).

**Comment by damianavila** [comment]
btw, thanks for testing, I will merge it soon.

**Comment by spex66** [comment]
Sorry didn't get it to work, or maybe I've the wrong expectation?
I've set the 'scroll' to True by 
```
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'theme': 'serif',
              'transition': 'zoom',
              'start_slideshow_at': 'selected',
              'scroll': True,
})
```

I've checked the ```livereveal.json``` that the value is stored correctly.
I restarted the kernel :)

But in my test case only the first cell is marked as "Slide", in reveal-mode I can see the other cells below.

But no way to scroll down.
I expect this to be a beginner problem, but happy to learn!
How can I scroll down in reveal mode on long pages?

Environment:
* win10, latest Chrome, latest jupyter deployed on top of Anaconda 2.7 64bit

thx for your help
(=PA=)

**Comment by damianavila** [comment]
>I've checked the livereveal.json that the value is stored correctly.

Can you paste the content here?

**Comment by spex66** [comment]
## the command from IPython Notebook
```
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'theme': 'serif',
              'transition': 'zoom',
              'start_slideshow_at': 'selected',
              'scroll': True,
})
```

## Resulting .jupyter\nbconfig\livereveal.json
```
{
  "theme": "serif", 
  "transition": "zoom", 
  "start_slideshow_at": "selected", 
  "scroll": true
}
```

**Comment by spex66** [comment]
Don't ask why... scrolling is working today.
Same browser, and same tab as yesterday...

Now I struggle to get "theme":"night" to have any effect, still all white.
It seems that I miss a trigger or something like that, to reload or refresh the config?
This would be an explaination to the scroll and theme problem.

```
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'theme': 'night',
              'transition': 'zoom',
              'start_slideshow_at': 'selected',
              'scroll': True,
})
```

The update of the livereveal.json file happens immediately after the above ```cm.update``` triggered.
Any idea, what is needed to get the change into effect on the next "ALT-r" action?

**Comment by spex66** [comment]
some CSS mess is going on... I tried to debug it in Chrome Dev Tools and it loads the correct theme CSS (like ```night.css```) but fails to apply all styles, like ```background-color```. 
And I've reloaded the browser window several time to be sure to cleaned caches :)

The ```<h4>``` for examples is updated with ```"font-family"``` on switching themes... but the ```background-color``` refuses, something is negating the theme setting again.

But this looks like a CSS problem, and maybe not so much RISE?

**Comment by spex66** [comment]
OK this is my body-tag, where I checked which CSS contributes the background-color to:
```
<body class="notebook_app  ctb_global_show command_mode rise-enabled" data-project="" data-base-url="/" data-ws-url="" data-notebook-name="test.ipynb" data-notebook-path="test.ipynb" style="overflow-y: auto; overflow-x: hidden;">
```

The ```.rise-enabled``` setting in ```main.css```
```
.rise-enabled {
  background-color: #fff;
...
```

is overriding / overruling the ```background-color``` from the theming like ```moon.css```.
But now my CSS knowledge comes to an full stop :(

Is it only me, having this problem?

**Comment by damianavila** [comment]
>Don't ask why... scrolling is working today.
>Same browser, and same tab as yesterday...

Maybe a browser cache issue, browsers are very aggresive caching things...

> Is it only me, having this problem?

Nop, the css problem with "darkish" themes is known... and was discussed previously, check here: #23, #51

**Comment by damianavila** [comment]
I have added a note at the README about this: #148

**Pull request merged**
