### PR TITLE
fix for correct invokation of sed on the MAC platform when running

### PR DESCRIPTION
**Pull request by parmentelat**
npm run reset-reveal
as per the development guide
https://github.com/damianavila/RISE#development

this was touched on in #282

### CODE REVIEW

**Comment by damianavila** [comment]
@mpacer, I think you reported me this personally some days ago.

**Comment by mpacer** [comment]
I have never seen a command line flag like that. No joke, I don't know how to interpret it. But I'll try it in a bit

**Comment by damianavila** [comment]
@mpacer I never saw it before as well :wink:

Here you have some interesting information about it: https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac/44864004#44864004

**Comment by mpacer** [comment]
sed with an I I've seen (that link is what I used to figure out that it wouldn't work on macOS but what's throwing me off is the `-i.upstream` never seen a dotted command line flag and don't know how to interpret it(even if it's no different)

**Comment by mpacer** [comment]
Oh I see it's a necessary argument to create the backup with that extension. Ok sounds good…

**Comment by parmentelat** [comment]
just to add that this relates to #280 as well

**Comment by damianavila** [comment]
Tested on linux and works. Merging now.

**Pull request merged**
