### PR TITLE
first docs

### PR DESCRIPTION
**Pull request by choldgraf**
First attempt! LMK what you think. Here's a sample:

http://predictablynoisy.com/RISE/

### CODE REVIEW

**Comment by damianavila** [comment]
Lovely!!

Just one thing, I think we need, at least, to put a small section about development stuff and, maybe, link to the README in case you don't want to paste all that info into the docs as well (that would be another interesting option).

**Comment by choldgraf** [comment]
sounds good - I'll give that a go in the next iteration on my flight. Now that a lot of this is in the documentation, what would like to keep in the README vs remove and point people to the documentation instead?

**Comment by damianavila** [comment]
> remove and point people to the documentation 

Yep... a tiny thing with references to the new docs :wink:

**Comment by choldgraf** [comment]
hey @damianavila , check it out now!

predictablynoisy.com/RISE

**Comment by choldgraf** [comment]
pinging @damianavila :-)

**Comment by damianavila** [comment]
LGTM, merging now.

**Comment by choldgraf** [comment]
cool! just FYI these won't go live until you push the `html` folder to the `gh-pages` branch. Alternatively you could set up readthedocs to build the website (though then the URL would be different from the one linked in the readme).

If you just wanna push to gh-pages, try https://github.com/davisp/ghp-import or check out https://github.com/drdoctr/doctr

(I don't think I can make these changes since I don't have push rights to the repo)

**Comment by damianavila** [comment]
I have already pushed it to gh-pages using a subtree approach I usually use for my blog: https://github.com/damianavila/RISE/blob/master/doc/README.md, but thanks for the suggestions!
And the PR!!

**Comment by choldgraf** [comment]
weird - for some reason the documentation in the README link didn't load before, but now it does. Hooray!

**Comment by damianavila** [comment]
> weird - for some reason the documentation in the README link didn't load before, but now it does. Hooray!

You had a wrong link... I corrected that in a new PR and merge it just some minutes ago :wink:

**Pull request merged**
