### PR TITLE
Scroll and start_slide_at fixes

### LINKED ISSUE #185: scrolling vertically
Hi,

I have some big code cells that won't fit vertically on one slide. Unfortunately I've found no way to scroll in presentation mode, but maybe I'm just missing some configuration option :).

best regards,
jochen

### PR DESCRIPTION
**Pull request by damianavila**
Scroll and some other config options were not getting the actual values because of timing issues. Solved putting all the config options where they can be read in a timely fashion.

Close #185

### CODE REVIEW

**Comment by dmardanbeigi** [comment]
still not working on safari 10.1. I have also set the scroll in the config file yet not able to do vertical scrolling
`mpl.rc("savefig", dpi=300)
from traitlets.config.manager import BaseJSONConfigManager
path = "/Users/Diako/.jupyter/nbconfig"
cm = BaseJSONConfigManager(config_dir=path)
cm.update('livereveal', {
              'scroll': True,'width': 1024,
              'height': 768,})`

**Comment by damianavila** [comment]
> still not working on safari 10.1

@dmardanbeigi, I don't have safari here to test this out, can you confirm me that it is actually working for you in Chrome of Firefox?

**Comment by dmardanbeigi** [comment]
not working on Chrome Version 58.0.3029.110 (64-bit) on mac.

**Comment by damianavila** [comment]
Can you run the following commands:
```
jupyter nbextension list
```
and
```
cat /Users/Diako/.jupyter/nbconfig/notebook.json 
cat /Users/Diako/.jupyter/nbconfig/livereveal.json 
```
Finally, in the notebook run these lines:

```python
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.read_config_path
```
and in another cell:
```python
cm.get('livereveal')
```

Thanks in advance.

**Comment by dmardanbeigi** [comment]
cm.get('livereveal') returns:

`{'height': 768,
 'scroll': True,
 'slideNumber': False,
 'start_slideshow_at': 'selected',
 'theme': 'sky',
 'transition': 'fade',
 'width': 1024}`

from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.read_config_path

returns:

`['/Users/Diako/.jupyter/nbconfig',
 '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/etc/jupyter/nbconfig',
 '/usr/local/etc/jupyter/nbconfig',
 '/etc/jupyter/nbconfig']`

and 
cat /Users/Diako/.jupyter/nbconfig/notebook.json 
cat /Users/Diako/.jupyter/nbconfig/livereveal.json 
returns:

`{
  "load_extensions": {
    "toc/toc": true,
    "nbextensions_configurator/config_menu/main": true,
    "jupyter-js-widgets/extension": true,
    "codefolding/main": true
  }
}
{
  "start_slideshow_at": "selected",
  "transition": "fade",
  "height": 768,
  "width": 1024,
  "theme": "sky",
  "slideNumber": false,
  "scroll": true
}
`

**Comment by damianavila** [comment]
@dmardanbeigi it the slideshow showing the `sky` theme, and more importantly, is it starting at the "selected" cell? I am starting to think around some kind of interaction with the other extensions you have installed there.

**Comment by damianavila** [comment]
Another things... you miss to run `jupyter nbextension list`, please post the output of that command.
Becuase I would expect some mentions of rise in you notebook.json file and I am not seeing it...

How did you install RISE to test this PR? Did you follow the dev instructions in the README?

**Comment by dmardanbeigi** [comment]
I installed the RISE by 
`pip3 install RISE`

the output of jupyter nbextension list is:
`Known nbextensions:
  config dir: /Users/Diako/.jupyter/nbconfig
    notebook section
      toc/toc  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      codefolding/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      rise/main  enabled 
      - Validating: OK`

and slideshow starts from the beginning with the sky theme

**Comment by damianavila** [comment]
> I installed the RISE by
>pip3 install RISE

OK, this is Pull Request... so the fix is not available from pip yet... after merging this one and other PRs I will release a new version and you will get the fix (if you upgrade).

**Comment by dmardanbeigi** [comment]
ahh.. alright. thanks

**Comment by damianavila** [comment]
Closing in favor of #259

**Pull request closed without merging**
